[Input]
useSpecialPad = false
cursorState = 1
deadZoneLeft = 2
deadZoneRight = 2
isMotionControlsEnabled = true
cursorHideTimeout = 5
backButtonBehavior = "left"
specialPadClass = 1

[General]
playBGM = false
logFilter = ""
BGMvolume = 50
FullscreenMode = "Borderless"
isPS4Pro = false
Fullscreen = false
isTrophyPopupDisabled = true
enableDiscordRPC = false
logType = "async"
userName = "Aldraius"
updateChannel = "Release"
chooseHomeTab = "General"
showSplash = true
autoUpdate = false
separateUpdateEnabled = true
compatibilityEnabled = true
checkCompatibilityOnStartup = true

[Keys]
TrophyKey = ""

[GPU]
dumpShaders = false
screenWidth = 1280
vblankDivider = 1
screenHeight = 720
nullGpu = false
patchShaders = true
copyGPUBuffers = false

[Vulkan]
validation_sync = false
gpuId = 0
hostMarkers = false
validation = false
crashDiagnostic = true
validation_gpu = false
rdocEnable = false
guestMarkers = false

[Settings]
consoleLanguage = 1

[GUI]
installDirs = ["B:\\PS4 ISOs"]
saveDataPath = ""
loadGameSizeEnabled = true
addonInstallDir = "B:\\PS4 ISOs\\DLCs"
emulatorLanguage = "en"
theme = 0
mw_width = 1280
mw_height = 720
iconSize = 164
sliderPos = 128
iconSizeGrid = 69
sliderPosGrid = 0
geometry_x =  391
gameTableMode = 0
pkgDirs = []
geometry_y = 164
geometry_w = 1280
geometry_h = 720
elfDirs = []
recentFiles = ["B:/PS4 ISOs/CUSA08809\\eboot.bin", "B:/PS4 ISOs/The Last of Us Remastered CUSA00552\\eboot.bin"]

[Debug]
DebugDump = false
CollectShader = false

